//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvtSubLedgerCAP_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvtSubLedgerCAP_Header()
        {
            this.InvtSubLedgerCAP_Details = new HashSet<InvtSubLedgerCAP_Details>();
        }
    
        public System.Guid HeaderId { get; set; }
        public string TxType { get; set; }
        public string TxNumber { get; set; }
        public Nullable<System.DateTime> TxDate { get; set; }
        public System.Guid StaffId { get; set; }
        public System.Guid WorkplaceId { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
        public bool ReadOnly { get; set; }
        public bool LinkToAP { get; set; }
        public string SupplierRefernce { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string TRF_REASON { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtSubLedgerCAP_Details> InvtSubLedgerCAP_Details { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Workplace Workplace { get; set; }
    }
}
