//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvtBatchTXF_Log
    {
        public System.Guid LogId { get; set; }
        public System.Guid DetailsId { get; set; }
        public Nullable<decimal> ReceivedQty { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public Nullable<System.Guid> ReceivedBy { get; set; }
    
        public virtual InvtBatchTXF_Details InvtBatchTXF_Details { get; set; }
    }
}
