//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvtBatchREC_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvtBatchREC_Header()
        {
            this.InvtBatchREC_Details = new HashSet<InvtBatchREC_Details>();
        }
    
        public System.Guid HeaderId { get; set; }
        public string TxType { get; set; }
        public string TxNumber { get; set; }
        public Nullable<System.DateTime> TxDate { get; set; }
        public System.Guid StaffId { get; set; }
        public System.Guid WorkplaceId { get; set; }
        public System.Guid SupplierId { get; set; }
        public string OrderNumber { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string PAYTYPE { get; set; }
        public Nullable<int> PAYTERM { get; set; }
        public Nullable<decimal> PAYDEPRATE { get; set; }
        public string PAYREMARK { get; set; }
        public string SHIPTERM { get; set; }
        public string SHIPREMARK { get; set; }
        public bool PARTIAL { get; set; }
        public Nullable<System.DateTime> OrderedOn { get; set; }
        public Nullable<System.DateTime> DeliverOn { get; set; }
        public Nullable<System.DateTime> CancelledOn { get; set; }
        public Nullable<decimal> GDISCOUNT1 { get; set; }
        public Nullable<decimal> GDISCOUNT2 { get; set; }
        public Nullable<decimal> GDISCOUNT3 { get; set; }
        public string SOURCE { get; set; }
        public Nullable<decimal> TOTALCOST { get; set; }
        public Nullable<decimal> TOTALQTY { get; set; }
        public bool SETTLEFLAG { get; set; }
        public Nullable<System.DateTime> SETTLEDATE { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public Nullable<System.Guid> PostedBy { get; set; }
        public string DELYADDRESS1 { get; set; }
        public string DELYADDRESS2 { get; set; }
        public string DELYADDRESS3 { get; set; }
        public string DELYADDRESS4 { get; set; }
        public string DELYCPN { get; set; }
        public string DELYTEL { get; set; }
        public Nullable<int> FREIGHTCHG { get; set; }
        public Nullable<int> HANDLINGCHG { get; set; }
        public Nullable<int> INSURCHG { get; set; }
        public Nullable<int> OTHCHG { get; set; }
        public Nullable<decimal> CHGCOEFF { get; set; }
        public Nullable<System.DateTime> RECDATE { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string SUPPINVNUM { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtBatchREC_Details> InvtBatchREC_Details { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Workplace Workplace { get; set; }
    }
}
