//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWorkplacePeriodicSummary
    {
        public System.Guid PeriodicSummaryId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid WorkplaceId { get; set; }
        public int FiscalYear { get; set; }
        public int Period { get; set; }
        public Nullable<System.DateTime> PeriodStartedOn { get; set; }
        public Nullable<System.DateTime> PeriodEndedOn { get; set; }
        public decimal BFQTY { get; set; }
        public decimal CDQTY { get; set; }
        public decimal FEPQTY { get; set; }
        public decimal RECQTY { get; set; }
        public decimal INVQTY { get; set; }
        public decimal POQTY { get; set; }
        public decimal SOQTY { get; set; }
        public decimal REJQTY { get; set; }
        public decimal EPQTY { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Workplace Workplace { get; set; }
    }
}
