//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductClass3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductClass3()
        {
            this.ProductClass31 = new HashSet<ProductClass3>();
            this.ProductCodes = new HashSet<ProductCode>();
        }
    
        public System.Guid Class3Id { get; set; }
        public Nullable<System.Guid> ParentClass { get; set; }
        public string Class3Code { get; set; }
        public string Class3Initial { get; set; }
        public string Class3Name { get; set; }
        public string Class3Name_Chs { get; set; }
        public string Class3Name_Cht { get; set; }
        public Nullable<System.Guid> AlternatedClass { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductClass3> ProductClass31 { get; set; }
        public virtual ProductClass3 ProductClass32 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCode> ProductCodes { get; set; }
    }
}
