//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartTag4Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SmartTag4Supplier()
        {
            this.SupplierSmartTag = new HashSet<SupplierSmartTag>();
            this.SmartTag4Supplier_Options = new HashSet<SmartTag4Supplier_Options>();
        }
    
        public System.Guid TagId { get; set; }
        public string TagCode { get; set; }
        public string TagName { get; set; }
        public string TagName_Chs { get; set; }
        public string TagName_Cht { get; set; }
        public int Priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierSmartTag> SupplierSmartTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SmartTag4Supplier_Options> SmartTag4Supplier_Options { get; set; }
    }
}
