//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInternetTag
    {
        public System.Guid TagId { get; set; }
        public System.Guid StaffId { get; set; }
        public Nullable<System.Guid> InternetTag1 { get; set; }
        public string InternetTag1Value { get; set; }
        public Nullable<System.Guid> InternetTag2 { get; set; }
        public string InternetTag2Value { get; set; }
        public Nullable<System.Guid> InternetTag3 { get; set; }
        public string InternetTag3Value { get; set; }
        public Nullable<System.Guid> InternetTag4 { get; set; }
        public string InternetTag4Value { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
