//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLabel
    {
        public System.Guid LabelId { get; set; }
        public string LanguageCode { get; set; }
        public string STKCODE { get; set; }
        public string CLASS1 { get; set; }
        public string CLASS2 { get; set; }
        public string CLASS3 { get; set; }
        public string CLASS4 { get; set; }
        public string CLASS5 { get; set; }
        public string CLASS6 { get; set; }
        public string APPENDIX1 { get; set; }
        public string APPENDIX2 { get; set; }
        public string APPENDIX3 { get; set; }
        public string SERIALNO { get; set; }
        public string VITEMNO { get; set; }
        public string COUPONNO { get; set; }
        public string DLFLAG { get; set; }
        public string REMARK1 { get; set; }
        public string REMARK2 { get; set; }
        public string REMARK3 { get; set; }
        public string REMARK4 { get; set; }
        public string REMARK5 { get; set; }
        public string REMARK6 { get; set; }
    }
}
