//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RT2020.EF6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workplace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workplace()
        {
            this.EPOSBatchHeaders = new HashSet<EPOSBatchHeader>();
            this.EPOSSubLedgerHeaders = new HashSet<EPOSSubLedgerHeader>();
            this.InvtBatchADJ_Header = new HashSet<InvtBatchADJ_Header>();
            this.InvtBatchCAP_Header = new HashSet<InvtBatchCAP_Header>();
            this.InvtBatchREC_Header = new HashSet<InvtBatchREC_Header>();
            this.InvtLedgerHeaders = new HashSet<InvtLedgerHeader>();
            this.InvtSubLedgerADJ_Header = new HashSet<InvtSubLedgerADJ_Header>();
            this.InvtSubLedgerCAP_Header = new HashSet<InvtSubLedgerCAP_Header>();
            this.InvtSubLedgerREC_Header = new HashSet<InvtSubLedgerREC_Header>();
            this.Members = new HashSet<Member>();
            this.PosLedgerHeaders = new HashSet<PosLedgerHeader>();
            this.ProductWorkplaces = new HashSet<ProductWorkplace>();
            this.ProductWorkplacePeriodicSummaries = new HashSet<ProductWorkplacePeriodicSummary>();
            this.PromotionPaymentFactors = new HashSet<PromotionPaymentFactor>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            this.PurchaseOrderReceiveHeaders = new HashSet<PurchaseOrderReceiveHeader>();
            this.StockTakeDetails = new HashSet<StockTakeDetail>();
            this.StockTakeHeaders = new HashSet<StockTakeHeader>();
            this.StocktakeHeader_HHT = new HashSet<StocktakeHeader_HHT>();
            this.WorkplaceAddresses = new HashSet<WorkplaceAddress>();
            this.WorkplaceSmartTags = new HashSet<WorkplaceSmartTag>();
        }
    
        public System.Guid WorkplaceId { get; set; }
        public System.Guid ZoneId { get; set; }
        public string WorkplaceCode { get; set; }
        public string WorkplaceInitial { get; set; }
        public string WorkplaceName { get; set; }
        public string WorkplaceName_Chs { get; set; }
        public string WorkplaceName_Cht { get; set; }
        public string AlternateWorkplaceCode { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public decimal BFQTY { get; set; }
        public decimal BFAMT { get; set; }
        public decimal CDQTY { get; set; }
        public decimal CDAMT { get; set; }
        public bool DownloadToPOS { get; set; }
        public bool DownloadToCounter { get; set; }
        public bool DownloadToShop { get; set; }
        public System.Guid NatureId { get; set; }
        public Nullable<System.Guid> LineOfOperationId { get; set; }
        public Nullable<int> Priority { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool Retired { get; set; }
        public Nullable<System.Guid> RetiredBy { get; set; }
        public Nullable<System.DateTime> RetiredOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPOSBatchHeader> EPOSBatchHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPOSSubLedgerHeader> EPOSSubLedgerHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtBatchADJ_Header> InvtBatchADJ_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtBatchCAP_Header> InvtBatchCAP_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtBatchREC_Header> InvtBatchREC_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtLedgerHeader> InvtLedgerHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtSubLedgerADJ_Header> InvtSubLedgerADJ_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtSubLedgerCAP_Header> InvtSubLedgerCAP_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvtSubLedgerREC_Header> InvtSubLedgerREC_Header { get; set; }
        public virtual LineOfOperation LineOfOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosLedgerHeader> PosLedgerHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkplace> ProductWorkplaces { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkplacePeriodicSummary> ProductWorkplacePeriodicSummaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionPaymentFactor> PromotionPaymentFactors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceiveHeader> PurchaseOrderReceiveHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTakeDetail> StockTakeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockTakeHeader> StockTakeHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StocktakeHeader_HHT> StocktakeHeader_HHT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkplaceAddress> WorkplaceAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkplaceSmartTag> WorkplaceSmartTags { get; set; }
        public virtual WorkplaceNature WorkplaceNature { get; set; }
        public virtual WorkplaceZone WorkplaceZone { get; set; }
    }
}
