using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.MemberVipLineOfOperation.
    /// Date Created:   2020-08-09 02:14:12
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class MemberVipLineOfOperation
    {
        private Guid key = Guid.Empty;
        private Guid vipLooId = Guid.Empty;
        private Guid memberVipId = Guid.Empty;
        private Guid lineOfOperationId = Guid.Empty;
        private decimal normalDiscount;
        private decimal promotionDiscount;

        /// <summary>
        /// Initialize an new empty MemberVipLineOfOperation object.
        /// </summary>
        public MemberVipLineOfOperation()
        {
        }
		
        /// <summary>
        /// Initialize a new MemberVipLineOfOperation object with the given parameters.
        /// </summary>
        public MemberVipLineOfOperation(Guid vipLooId, Guid memberVipId, Guid lineOfOperationId, decimal normalDiscount, decimal promotionDiscount)
        {
                this.vipLooId = vipLooId;
                this.memberVipId = memberVipId;
                this.lineOfOperationId = lineOfOperationId;
                this.normalDiscount = normalDiscount;
                this.promotionDiscount = promotionDiscount;
        }	
		
        /// <summary>
        /// Loads a MemberVipLineOfOperation object from the database using the given VipLooId
        /// </summary>
        /// <param name="vipLooId">The primary key value</param>
        /// <returns>A MemberVipLineOfOperation object</returns>
        public static MemberVipLineOfOperation Load(Guid vipLooId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@VipLooId", vipLooId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spMemberVipLineOfOperation_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    MemberVipLineOfOperation result = new MemberVipLineOfOperation();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a MemberVipLineOfOperation object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A MemberVipLineOfOperation object</returns>
        public static MemberVipLineOfOperation LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spMemberVipLineOfOperation_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    MemberVipLineOfOperation result = new MemberVipLineOfOperation();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of MemberVipLineOfOperation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the MemberVipLineOfOperation objects in the database.</returns>
        public static MemberVipLineOfOperationCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spMemberVipLineOfOperation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of MemberVipLineOfOperation objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the MemberVipLineOfOperation objects in the database ordered by the columns specified.</returns>
        public static MemberVipLineOfOperationCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spMemberVipLineOfOperation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of MemberVipLineOfOperation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the MemberVipLineOfOperation objects in the database.</returns>
        public static MemberVipLineOfOperationCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spMemberVipLineOfOperation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of MemberVipLineOfOperation objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the MemberVipLineOfOperation objects in the database ordered by the columns specified.</returns>
        public static MemberVipLineOfOperationCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spMemberVipLineOfOperation_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of MemberVipLineOfOperation objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the MemberVipLineOfOperation objects in the database.</returns>
        public static MemberVipLineOfOperationCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            MemberVipLineOfOperationCollection result = new MemberVipLineOfOperationCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    MemberVipLineOfOperation tmp = new MemberVipLineOfOperation();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a MemberVipLineOfOperation object from the database.
        /// </summary>
        /// <param name="vipLooId">The primary key value</param>
        public static void Delete(Guid vipLooId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@VipLooId", vipLooId) };
            SqlHelper.Default.ExecuteNonQuery("spMemberVipLineOfOperation_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) vipLooId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) memberVipId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) lineOfOperationId = reader.GetGuid(2);
                if (!reader.IsDBNull(3)) normalDiscount = reader.GetDecimal(3);
                if (!reader.IsDBNull(4)) promotionDiscount = reader.GetDecimal(4);
            }
        }
		
        public void Delete()
        {
            Delete(this.VipLooId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != VipLooId)
                    this.Delete();
                Update();
            }
        }

        public Guid VipLooId
        {
            get { return vipLooId; }
            set { vipLooId = value; }
        }

        public Guid MemberVipId
        {
            get { return memberVipId; }
            set { memberVipId = value; }
        }

        public Guid LineOfOperationId
        {
            get { return lineOfOperationId; }
            set { lineOfOperationId = value; }
        }

        public decimal NormalDiscount
        {
            get { return normalDiscount; }
            set { normalDiscount = value; }
        }

        public decimal PromotionDiscount
        {
            get { return promotionDiscount; }
            set { promotionDiscount = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spMemberVipLineOfOperation_InsRec", "@VipLooId", out returnedValue, parameterValues);
            
            vipLooId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spMemberVipLineOfOperation_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[5];
            prams[0] = GetSqlParameter("@VipLooId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.VipLooId);
            prams[1] = GetSqlParameter("@MemberVipId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.MemberVipId);
            prams[2] = GetSqlParameter("@LineOfOperationId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.LineOfOperationId);
            prams[3] = GetSqlParameter("@NormalDiscount", ParameterDirection.Input, SqlDbType.Decimal, 9, this.NormalDiscount);
            prams[4] = GetSqlParameter("@PromotionDiscount", ParameterDirection.Input, SqlDbType.Decimal, 9, this.PromotionDiscount);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@VipLooId", SqlDbType.UniqueIdentifier, 16, this.VipLooId),
                GetSqlParameterWithoutDirection("@MemberVipId", SqlDbType.UniqueIdentifier, 16, this.MemberVipId),
                GetSqlParameterWithoutDirection("@LineOfOperationId", SqlDbType.UniqueIdentifier, 16, this.LineOfOperationId),
                GetSqlParameterWithoutDirection("@NormalDiscount", SqlDbType.Decimal, 9, this.NormalDiscount),
                GetSqlParameterWithoutDirection("@PromotionDiscount", SqlDbType.Decimal, 9, this.PromotionDiscount)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("vipLooId: " + vipLooId.ToString()).Append("\r\n");
            builder.Append("memberVipId: " + memberVipId.ToString()).Append("\r\n");
            builder.Append("lineOfOperationId: " + lineOfOperationId.ToString()).Append("\r\n");
            builder.Append("normalDiscount: " + normalDiscount.ToString()).Append("\r\n");
            builder.Append("promotionDiscount: " + promotionDiscount.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			MemberVipLineOfOperationCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = MemberVipLineOfOperation.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = MemberVipLineOfOperation.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (MemberVipLineOfOperation item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.MemberVipId != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.VipLooId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(MemberVipLineOfOperation target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.MemberVipId == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				MemberVipLineOfOperation parentTemplate = MemberVipLineOfOperation.Load(target.MemberVipId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(MemberVipLineOfOperation target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="MemberVipLineOfOperation">MemberVipLineOfOperation</see> objects.
    /// </summary>
    public class MemberVipLineOfOperationCollection : BindingList< MemberVipLineOfOperation>
    {
	}
}
