using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.PhoneTag.
    /// Date Created:   2020-08-09 02:14:12
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class PhoneTag
    {
        private Guid key = Guid.Empty;
        private Guid phoneTagId = Guid.Empty;
        private string phoneCode = String.Empty;
        private string phoneName = String.Empty;
        private string phoneName_Chs = String.Empty;
        private string phoneName_Cht = String.Empty;
        private int priority = 0;

        /// <summary>
        /// Initialize an new empty PhoneTag object.
        /// </summary>
        public PhoneTag()
        {
        }
		
        /// <summary>
        /// Initialize a new PhoneTag object with the given parameters.
        /// </summary>
        public PhoneTag(Guid phoneTagId, string phoneCode, string phoneName, string phoneName_Chs, string phoneName_Cht, int priority)
        {
                this.phoneTagId = phoneTagId;
                this.phoneCode = phoneCode;
                this.phoneName = phoneName;
                this.phoneName_Chs = phoneName_Chs;
                this.phoneName_Cht = phoneName_Cht;
                this.priority = priority;
        }	
		
        /// <summary>
        /// Loads a PhoneTag object from the database using the given PhoneTagId
        /// </summary>
        /// <param name="phoneTagId">The primary key value</param>
        /// <returns>A PhoneTag object</returns>
        public static PhoneTag Load(Guid phoneTagId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@PhoneTagId", phoneTagId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPhoneTag_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    PhoneTag result = new PhoneTag();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a PhoneTag object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A PhoneTag object</returns>
        public static PhoneTag LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPhoneTag_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    PhoneTag result = new PhoneTag();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of PhoneTag objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PhoneTag objects in the database.</returns>
        public static PhoneTagCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spPhoneTag_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PhoneTag objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PhoneTag objects in the database ordered by the columns specified.</returns>
        public static PhoneTagCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPhoneTag_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PhoneTag objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PhoneTag objects in the database.</returns>
        public static PhoneTagCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spPhoneTag_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PhoneTag objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PhoneTag objects in the database ordered by the columns specified.</returns>
        public static PhoneTagCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPhoneTag_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PhoneTag objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PhoneTag objects in the database.</returns>
        public static PhoneTagCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            PhoneTagCollection result = new PhoneTagCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    PhoneTag tmp = new PhoneTag();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a PhoneTag object from the database.
        /// </summary>
        /// <param name="phoneTagId">The primary key value</param>
        public static void Delete(Guid phoneTagId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@PhoneTagId", phoneTagId) };
            SqlHelper.Default.ExecuteNonQuery("spPhoneTag_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) phoneTagId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) phoneCode = reader.GetString(1);
                if (!reader.IsDBNull(2)) phoneName = reader.GetString(2);
                if (!reader.IsDBNull(3)) phoneName_Chs = reader.GetString(3);
                if (!reader.IsDBNull(4)) phoneName_Cht = reader.GetString(4);
                if (!reader.IsDBNull(5)) priority = reader.GetInt32(5);
            }
        }
		
        public void Delete()
        {
            Delete(this.PhoneTagId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != PhoneTagId)
                    this.Delete();
                Update();
            }
        }

        public Guid PhoneTagId
        {
            get { return phoneTagId; }
            set { phoneTagId = value; }
        }

        public string PhoneCode
        {
            get { return phoneCode; }
            set { phoneCode = value; }
        }

        public string PhoneName
        {
            get { return phoneName; }
            set { phoneName = value; }
        }

        public string PhoneName_Chs
        {
            get { return phoneName_Chs; }
            set { phoneName_Chs = value; }
        }

        public string PhoneName_Cht
        {
            get { return phoneName_Cht; }
            set { phoneName_Cht = value; }
        }

        public int Priority
        {
            get { return priority; }
            set { priority = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spPhoneTag_InsRec", "@PhoneTagId", out returnedValue, parameterValues);
            
            phoneTagId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spPhoneTag_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@PhoneTagId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.PhoneTagId);
            prams[1] = GetSqlParameter("@PhoneCode", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.PhoneCode);
            prams[2] = GetSqlParameter("@PhoneName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.PhoneName);
            prams[3] = GetSqlParameter("@PhoneName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.PhoneName_Chs);
            prams[4] = GetSqlParameter("@PhoneName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.PhoneName_Cht);
            prams[5] = GetSqlParameter("@Priority", ParameterDirection.Input, SqlDbType.Int, 4, this.Priority);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@PhoneTagId", SqlDbType.UniqueIdentifier, 16, this.PhoneTagId),
                GetSqlParameterWithoutDirection("@PhoneCode", SqlDbType.NVarChar, 10, this.PhoneCode),
                GetSqlParameterWithoutDirection("@PhoneName", SqlDbType.NVarChar, 64, this.PhoneName),
                GetSqlParameterWithoutDirection("@PhoneName_Chs", SqlDbType.NVarChar, 64, this.PhoneName_Chs),
                GetSqlParameterWithoutDirection("@PhoneName_Cht", SqlDbType.NVarChar, 64, this.PhoneName_Cht),
                GetSqlParameterWithoutDirection("@Priority", SqlDbType.Int, 4, this.Priority)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("phoneTagId: " + phoneTagId.ToString()).Append("\r\n");
            builder.Append("phoneCode: " + phoneCode.ToString()).Append("\r\n");
            builder.Append("phoneName: " + phoneName.ToString()).Append("\r\n");
            builder.Append("phoneName_Chs: " + phoneName_Chs.ToString()).Append("\r\n");
            builder.Append("phoneName_Cht: " + phoneName_Cht.ToString()).Append("\r\n");
            builder.Append("priority: " + priority.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			PhoneTagCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = PhoneTag.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = PhoneTag.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (PhoneTag item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = IgnorThis(item, ParentFilter);
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.PhoneTagId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(PhoneTag target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
			string filterField = (string)pi.GetValue(target, null);
			if (filterField.ToLower() == parsed[1].ToLower())
			{
				result = false;
			}
			return result;
		}

		private static string GetFormatedText(PhoneTag target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="PhoneTag">PhoneTag</see> objects.
    /// </summary>
    public class PhoneTagCollection : BindingList< PhoneTag>
    {
	}
}
