using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.PosLedgerAnalysis.
    /// Date Created:   2020-08-09 02:14:12
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class PosLedgerAnalysis
    {
        private Guid key = Guid.Empty;
        private Guid analysisId = Guid.Empty;
        private Guid headerId = Guid.Empty;
        private string code01 = String.Empty;
        private string code02 = String.Empty;
        private string code03 = String.Empty;
        private string code04 = String.Empty;
        private string code05 = String.Empty;
        private string code06 = String.Empty;
        private string code07 = String.Empty;
        private string code08 = String.Empty;
        private string code09 = String.Empty;
        private string code10 = String.Empty;

        /// <summary>
        /// Initialize an new empty PosLedgerAnalysis object.
        /// </summary>
        public PosLedgerAnalysis()
        {
        }
		
        /// <summary>
        /// Initialize a new PosLedgerAnalysis object with the given parameters.
        /// </summary>
        public PosLedgerAnalysis(Guid analysisId, Guid headerId, string code01, string code02, string code03, string code04, string code05, string code06, string code07, string code08, string code09, string code10)
        {
                this.analysisId = analysisId;
                this.headerId = headerId;
                this.code01 = code01;
                this.code02 = code02;
                this.code03 = code03;
                this.code04 = code04;
                this.code05 = code05;
                this.code06 = code06;
                this.code07 = code07;
                this.code08 = code08;
                this.code09 = code09;
                this.code10 = code10;
        }	
		
        /// <summary>
        /// Loads a PosLedgerAnalysis object from the database using the given AnalysisId
        /// </summary>
        /// <param name="analysisId">The primary key value</param>
        /// <returns>A PosLedgerAnalysis object</returns>
        public static PosLedgerAnalysis Load(Guid analysisId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@AnalysisId", analysisId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPosLedgerAnalysis_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    PosLedgerAnalysis result = new PosLedgerAnalysis();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a PosLedgerAnalysis object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A PosLedgerAnalysis object</returns>
        public static PosLedgerAnalysis LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPosLedgerAnalysis_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    PosLedgerAnalysis result = new PosLedgerAnalysis();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of PosLedgerAnalysis objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosLedgerAnalysis objects in the database.</returns>
        public static PosLedgerAnalysisCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spPosLedgerAnalysis_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosLedgerAnalysis objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PosLedgerAnalysis objects in the database ordered by the columns specified.</returns>
        public static PosLedgerAnalysisCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPosLedgerAnalysis_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosLedgerAnalysis objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosLedgerAnalysis objects in the database.</returns>
        public static PosLedgerAnalysisCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spPosLedgerAnalysis_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosLedgerAnalysis objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PosLedgerAnalysis objects in the database ordered by the columns specified.</returns>
        public static PosLedgerAnalysisCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPosLedgerAnalysis_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PosLedgerAnalysis objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PosLedgerAnalysis objects in the database.</returns>
        public static PosLedgerAnalysisCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            PosLedgerAnalysisCollection result = new PosLedgerAnalysisCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    PosLedgerAnalysis tmp = new PosLedgerAnalysis();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a PosLedgerAnalysis object from the database.
        /// </summary>
        /// <param name="analysisId">The primary key value</param>
        public static void Delete(Guid analysisId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@AnalysisId", analysisId) };
            SqlHelper.Default.ExecuteNonQuery("spPosLedgerAnalysis_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) analysisId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) headerId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) code01 = reader.GetString(2);
                if (!reader.IsDBNull(3)) code02 = reader.GetString(3);
                if (!reader.IsDBNull(4)) code03 = reader.GetString(4);
                if (!reader.IsDBNull(5)) code04 = reader.GetString(5);
                if (!reader.IsDBNull(6)) code05 = reader.GetString(6);
                if (!reader.IsDBNull(7)) code06 = reader.GetString(7);
                if (!reader.IsDBNull(8)) code07 = reader.GetString(8);
                if (!reader.IsDBNull(9)) code08 = reader.GetString(9);
                if (!reader.IsDBNull(10)) code09 = reader.GetString(10);
                if (!reader.IsDBNull(11)) code10 = reader.GetString(11);
            }
        }
		
        public void Delete()
        {
            Delete(this.AnalysisId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != AnalysisId)
                    this.Delete();
                Update();
            }
        }

        public Guid AnalysisId
        {
            get { return analysisId; }
            set { analysisId = value; }
        }

        public Guid HeaderId
        {
            get { return headerId; }
            set { headerId = value; }
        }

        public string Code01
        {
            get { return code01; }
            set { code01 = value; }
        }

        public string Code02
        {
            get { return code02; }
            set { code02 = value; }
        }

        public string Code03
        {
            get { return code03; }
            set { code03 = value; }
        }

        public string Code04
        {
            get { return code04; }
            set { code04 = value; }
        }

        public string Code05
        {
            get { return code05; }
            set { code05 = value; }
        }

        public string Code06
        {
            get { return code06; }
            set { code06 = value; }
        }

        public string Code07
        {
            get { return code07; }
            set { code07 = value; }
        }

        public string Code08
        {
            get { return code08; }
            set { code08 = value; }
        }

        public string Code09
        {
            get { return code09; }
            set { code09 = value; }
        }

        public string Code10
        {
            get { return code10; }
            set { code10 = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spPosLedgerAnalysis_InsRec", "@AnalysisId", out returnedValue, parameterValues);
            
            analysisId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spPosLedgerAnalysis_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[12];
            prams[0] = GetSqlParameter("@AnalysisId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.AnalysisId);
            prams[1] = GetSqlParameter("@HeaderId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.HeaderId);
            prams[2] = GetSqlParameter("@Code01", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code01);
            prams[3] = GetSqlParameter("@Code02", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code02);
            prams[4] = GetSqlParameter("@Code03", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code03);
            prams[5] = GetSqlParameter("@Code04", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code04);
            prams[6] = GetSqlParameter("@Code05", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code05);
            prams[7] = GetSqlParameter("@Code06", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code06);
            prams[8] = GetSqlParameter("@Code07", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code07);
            prams[9] = GetSqlParameter("@Code08", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code08);
            prams[10] = GetSqlParameter("@Code09", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code09);
            prams[11] = GetSqlParameter("@Code10", ParameterDirection.Input, SqlDbType.VarChar, 2, this.Code10);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@AnalysisId", SqlDbType.UniqueIdentifier, 16, this.AnalysisId),
                GetSqlParameterWithoutDirection("@HeaderId", SqlDbType.UniqueIdentifier, 16, this.HeaderId),
                GetSqlParameterWithoutDirection("@Code01", SqlDbType.VarChar, 2, this.Code01),
                GetSqlParameterWithoutDirection("@Code02", SqlDbType.VarChar, 2, this.Code02),
                GetSqlParameterWithoutDirection("@Code03", SqlDbType.VarChar, 2, this.Code03),
                GetSqlParameterWithoutDirection("@Code04", SqlDbType.VarChar, 2, this.Code04),
                GetSqlParameterWithoutDirection("@Code05", SqlDbType.VarChar, 2, this.Code05),
                GetSqlParameterWithoutDirection("@Code06", SqlDbType.VarChar, 2, this.Code06),
                GetSqlParameterWithoutDirection("@Code07", SqlDbType.VarChar, 2, this.Code07),
                GetSqlParameterWithoutDirection("@Code08", SqlDbType.VarChar, 2, this.Code08),
                GetSqlParameterWithoutDirection("@Code09", SqlDbType.VarChar, 2, this.Code09),
                GetSqlParameterWithoutDirection("@Code10", SqlDbType.VarChar, 2, this.Code10)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("analysisId: " + analysisId.ToString()).Append("\r\n");
            builder.Append("headerId: " + headerId.ToString()).Append("\r\n");
            builder.Append("code01: " + code01.ToString()).Append("\r\n");
            builder.Append("code02: " + code02.ToString()).Append("\r\n");
            builder.Append("code03: " + code03.ToString()).Append("\r\n");
            builder.Append("code04: " + code04.ToString()).Append("\r\n");
            builder.Append("code05: " + code05.ToString()).Append("\r\n");
            builder.Append("code06: " + code06.ToString()).Append("\r\n");
            builder.Append("code07: " + code07.ToString()).Append("\r\n");
            builder.Append("code08: " + code08.ToString()).Append("\r\n");
            builder.Append("code09: " + code09.ToString()).Append("\r\n");
            builder.Append("code10: " + code10.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			PosLedgerAnalysisCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = PosLedgerAnalysis.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = PosLedgerAnalysis.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (PosLedgerAnalysis item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.HeaderId != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.AnalysisId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(PosLedgerAnalysis target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.HeaderId == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				PosLedgerAnalysis parentTemplate = PosLedgerAnalysis.Load(target.HeaderId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(PosLedgerAnalysis target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="PosLedgerAnalysis">PosLedgerAnalysis</see> objects.
    /// </summary>
    public class PosLedgerAnalysisCollection : BindingList< PosLedgerAnalysis>
    {
	}
}
