using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.ProductDim_Details.
    /// Date Created:   2020-08-09 02:14:14
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class ProductDim_Details
    {
        private Guid key = Guid.Empty;
        private Guid dimDetailId = Guid.Empty;
        private Guid dimensionId = Guid.Empty;
        private string aPPENDIX1 = String.Empty;
        private string aPPENDIX2 = String.Empty;
        private string aPPENDIX3 = String.Empty;

        /// <summary>
        /// Initialize an new empty ProductDim_Details object.
        /// </summary>
        public ProductDim_Details()
        {
        }
		
        /// <summary>
        /// Initialize a new ProductDim_Details object with the given parameters.
        /// </summary>
        public ProductDim_Details(Guid dimDetailId, Guid dimensionId, string aPPENDIX1, string aPPENDIX2, string aPPENDIX3)
        {
                this.dimDetailId = dimDetailId;
                this.dimensionId = dimensionId;
                this.aPPENDIX1 = aPPENDIX1;
                this.aPPENDIX2 = aPPENDIX2;
                this.aPPENDIX3 = aPPENDIX3;
        }	
		
        /// <summary>
        /// Loads a ProductDim_Details object from the database using the given DimDetailId
        /// </summary>
        /// <param name="dimDetailId">The primary key value</param>
        /// <returns>A ProductDim_Details object</returns>
        public static ProductDim_Details Load(Guid dimDetailId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@DimDetailId", dimDetailId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spProductDim_Details_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    ProductDim_Details result = new ProductDim_Details();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a ProductDim_Details object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A ProductDim_Details object</returns>
        public static ProductDim_Details LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spProductDim_Details_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    ProductDim_Details result = new ProductDim_Details();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of ProductDim_Details objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductDim_Details objects in the database.</returns>
        public static ProductDim_DetailsCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spProductDim_Details_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductDim_Details objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ProductDim_Details objects in the database ordered by the columns specified.</returns>
        public static ProductDim_DetailsCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spProductDim_Details_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductDim_Details objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductDim_Details objects in the database.</returns>
        public static ProductDim_DetailsCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spProductDim_Details_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductDim_Details objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ProductDim_Details objects in the database ordered by the columns specified.</returns>
        public static ProductDim_DetailsCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spProductDim_Details_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductDim_Details objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductDim_Details objects in the database.</returns>
        public static ProductDim_DetailsCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ProductDim_DetailsCollection result = new ProductDim_DetailsCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    ProductDim_Details tmp = new ProductDim_Details();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a ProductDim_Details object from the database.
        /// </summary>
        /// <param name="dimDetailId">The primary key value</param>
        public static void Delete(Guid dimDetailId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@DimDetailId", dimDetailId) };
            SqlHelper.Default.ExecuteNonQuery("spProductDim_Details_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) dimDetailId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) dimensionId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) aPPENDIX1 = reader.GetString(2);
                if (!reader.IsDBNull(3)) aPPENDIX2 = reader.GetString(3);
                if (!reader.IsDBNull(4)) aPPENDIX3 = reader.GetString(4);
            }
        }
		
        public void Delete()
        {
            Delete(this.DimDetailId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != DimDetailId)
                    this.Delete();
                Update();
            }
        }

        public Guid DimDetailId
        {
            get { return dimDetailId; }
            set { dimDetailId = value; }
        }

        public Guid DimensionId
        {
            get { return dimensionId; }
            set { dimensionId = value; }
        }

        public string APPENDIX1
        {
            get { return aPPENDIX1; }
            set { aPPENDIX1 = value; }
        }

        public string APPENDIX2
        {
            get { return aPPENDIX2; }
            set { aPPENDIX2 = value; }
        }

        public string APPENDIX3
        {
            get { return aPPENDIX3; }
            set { aPPENDIX3 = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spProductDim_Details_InsRec", "@DimDetailId", out returnedValue, parameterValues);
            
            dimDetailId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spProductDim_Details_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[5];
            prams[0] = GetSqlParameter("@DimDetailId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.DimDetailId);
            prams[1] = GetSqlParameter("@DimensionId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.DimensionId);
            prams[2] = GetSqlParameter("@APPENDIX1", ParameterDirection.Input, SqlDbType.VarChar, 4, this.APPENDIX1);
            prams[3] = GetSqlParameter("@APPENDIX2", ParameterDirection.Input, SqlDbType.VarChar, 4, this.APPENDIX2);
            prams[4] = GetSqlParameter("@APPENDIX3", ParameterDirection.Input, SqlDbType.VarChar, 4, this.APPENDIX3);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@DimDetailId", SqlDbType.UniqueIdentifier, 16, this.DimDetailId),
                GetSqlParameterWithoutDirection("@DimensionId", SqlDbType.UniqueIdentifier, 16, this.DimensionId),
                GetSqlParameterWithoutDirection("@APPENDIX1", SqlDbType.VarChar, 4, this.APPENDIX1),
                GetSqlParameterWithoutDirection("@APPENDIX2", SqlDbType.VarChar, 4, this.APPENDIX2),
                GetSqlParameterWithoutDirection("@APPENDIX3", SqlDbType.VarChar, 4, this.APPENDIX3)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("dimDetailId: " + dimDetailId.ToString()).Append("\r\n");
            builder.Append("dimensionId: " + dimensionId.ToString()).Append("\r\n");
            builder.Append("aPPENDIX1: " + aPPENDIX1.ToString()).Append("\r\n");
            builder.Append("aPPENDIX2: " + aPPENDIX2.ToString()).Append("\r\n");
            builder.Append("aPPENDIX3: " + aPPENDIX3.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			ProductDim_DetailsCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = ProductDim_Details.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = ProductDim_Details.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (ProductDim_Details item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.DimensionId != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.DimDetailId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(ProductDim_Details target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.DimensionId == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				ProductDim_Details parentTemplate = ProductDim_Details.Load(target.DimensionId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(ProductDim_Details target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="ProductDim_Details">ProductDim_Details</see> objects.
    /// </summary>
    public class ProductDim_DetailsCollection : BindingList< ProductDim_Details>
    {
	}
}
