using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.ProductNature.
    /// Date Created:   2020-08-09 02:14:14
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class ProductNature
    {
        private Guid key = Guid.Empty;
        private Guid natureId = Guid.Empty;
        private Guid parentNature = Guid.Empty;
        private string natureCode = String.Empty;
        private string natureName = String.Empty;
        private string natureName_Chs = String.Empty;
        private string natureName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty ProductNature object.
        /// </summary>
        public ProductNature()
        {
        }
		
        /// <summary>
        /// Initialize a new ProductNature object with the given parameters.
        /// </summary>
        public ProductNature(Guid natureId, Guid parentNature, string natureCode, string natureName, string natureName_Chs, string natureName_Cht)
        {
                this.natureId = natureId;
                this.parentNature = parentNature;
                this.natureCode = natureCode;
                this.natureName = natureName;
                this.natureName_Chs = natureName_Chs;
                this.natureName_Cht = natureName_Cht;
        }	
		
        /// <summary>
        /// Loads a ProductNature object from the database using the given NatureId
        /// </summary>
        /// <param name="natureId">The primary key value</param>
        /// <returns>A ProductNature object</returns>
        public static ProductNature Load(Guid natureId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@NatureId", natureId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spProductNature_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    ProductNature result = new ProductNature();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a ProductNature object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A ProductNature object</returns>
        public static ProductNature LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spProductNature_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    ProductNature result = new ProductNature();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of ProductNature objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductNature objects in the database.</returns>
        public static ProductNatureCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spProductNature_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductNature objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ProductNature objects in the database ordered by the columns specified.</returns>
        public static ProductNatureCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spProductNature_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductNature objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductNature objects in the database.</returns>
        public static ProductNatureCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spProductNature_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductNature objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ProductNature objects in the database ordered by the columns specified.</returns>
        public static ProductNatureCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spProductNature_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ProductNature objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ProductNature objects in the database.</returns>
        public static ProductNatureCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ProductNatureCollection result = new ProductNatureCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    ProductNature tmp = new ProductNature();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a ProductNature object from the database.
        /// </summary>
        /// <param name="natureId">The primary key value</param>
        public static void Delete(Guid natureId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@NatureId", natureId) };
            SqlHelper.Default.ExecuteNonQuery("spProductNature_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) natureId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentNature = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) natureCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) natureName = reader.GetString(3);
                if (!reader.IsDBNull(4)) natureName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) natureName_Cht = reader.GetString(5);
            }
        }
		
        public void Delete()
        {
            Delete(this.NatureId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != NatureId)
                    this.Delete();
                Update();
            }
        }

        public Guid NatureId
        {
            get { return natureId; }
            set { natureId = value; }
        }

        public Guid ParentNature
        {
            get { return parentNature; }
            set { parentNature = value; }
        }

        public string NatureCode
        {
            get { return natureCode; }
            set { natureCode = value; }
        }

        public string NatureName
        {
            get { return natureName; }
            set { natureName = value; }
        }

        public string NatureName_Chs
        {
            get { return natureName_Chs; }
            set { natureName_Chs = value; }
        }

        public string NatureName_Cht
        {
            get { return natureName_Cht; }
            set { natureName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spProductNature_InsRec", "@NatureId", out returnedValue, parameterValues);
            
            natureId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spProductNature_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@NatureId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.NatureId);
            prams[1] = GetSqlParameter("@ParentNature", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentNature);
            prams[2] = GetSqlParameter("@NatureCode", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.NatureCode);
            prams[3] = GetSqlParameter("@NatureName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.NatureName);
            prams[4] = GetSqlParameter("@NatureName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.NatureName_Chs);
            prams[5] = GetSqlParameter("@NatureName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.NatureName_Cht);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@NatureId", SqlDbType.UniqueIdentifier, 16, this.NatureId),
                GetSqlParameterWithoutDirection("@ParentNature", SqlDbType.UniqueIdentifier, 16, this.ParentNature),
                GetSqlParameterWithoutDirection("@NatureCode", SqlDbType.NVarChar, 10, this.NatureCode),
                GetSqlParameterWithoutDirection("@NatureName", SqlDbType.NVarChar, 64, this.NatureName),
                GetSqlParameterWithoutDirection("@NatureName_Chs", SqlDbType.NVarChar, 64, this.NatureName_Chs),
                GetSqlParameterWithoutDirection("@NatureName_Cht", SqlDbType.NVarChar, 64, this.NatureName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("natureId: " + natureId.ToString()).Append("\r\n");
            builder.Append("parentNature: " + parentNature.ToString()).Append("\r\n");
            builder.Append("natureCode: " + natureCode.ToString()).Append("\r\n");
            builder.Append("natureName: " + natureName.ToString()).Append("\r\n");
            builder.Append("natureName_Chs: " + natureName_Chs.ToString()).Append("\r\n");
            builder.Append("natureName_Cht: " + natureName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			ProductNatureCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = ProductNature.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = ProductNature.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (ProductNature item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.ParentNature != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.NatureId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(ProductNature target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.ParentNature == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				ProductNature parentTemplate = ProductNature.Load(target.ParentNature);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(ProductNature target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="ProductNature">ProductNature</see> objects.
    /// </summary>
    public class ProductNatureCollection : BindingList< ProductNature>
    {
	}
}
