using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.PurchaseOrderReceiveDetails.
    /// Date Created:   2020-08-09 02:14:15
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class PurchaseOrderReceiveDetails
    {
        private Guid key = Guid.Empty;
        private Guid receiveDetailsId = Guid.Empty;
        private Guid receiveHeaderId = Guid.Empty;
        private int lineNumber = 0;
        private Guid productId = Guid.Empty;
        private decimal receivedQty;
        private decimal unitCost;
        private decimal discountPcn;
        private decimal netUnitCost;
        private decimal netUnitCostCoefficient;
        private decimal billQty;
        private decimal billUnitAmount;
        private string notes = String.Empty;

        /// <summary>
        /// Initialize an new empty PurchaseOrderReceiveDetails object.
        /// </summary>
        public PurchaseOrderReceiveDetails()
        {
        }
		
        /// <summary>
        /// Initialize a new PurchaseOrderReceiveDetails object with the given parameters.
        /// </summary>
        public PurchaseOrderReceiveDetails(Guid receiveDetailsId, Guid receiveHeaderId, int lineNumber, Guid productId, decimal receivedQty, decimal unitCost, decimal discountPcn, decimal netUnitCost, decimal netUnitCostCoefficient, decimal billQty, decimal billUnitAmount, string notes)
        {
                this.receiveDetailsId = receiveDetailsId;
                this.receiveHeaderId = receiveHeaderId;
                this.lineNumber = lineNumber;
                this.productId = productId;
                this.receivedQty = receivedQty;
                this.unitCost = unitCost;
                this.discountPcn = discountPcn;
                this.netUnitCost = netUnitCost;
                this.netUnitCostCoefficient = netUnitCostCoefficient;
                this.billQty = billQty;
                this.billUnitAmount = billUnitAmount;
                this.notes = notes;
        }	
		
        /// <summary>
        /// Loads a PurchaseOrderReceiveDetails object from the database using the given ReceiveDetailsId
        /// </summary>
        /// <param name="receiveDetailsId">The primary key value</param>
        /// <returns>A PurchaseOrderReceiveDetails object</returns>
        public static PurchaseOrderReceiveDetails Load(Guid receiveDetailsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ReceiveDetailsId", receiveDetailsId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPurchaseOrderReceiveDetails_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    PurchaseOrderReceiveDetails result = new PurchaseOrderReceiveDetails();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a PurchaseOrderReceiveDetails object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A PurchaseOrderReceiveDetails object</returns>
        public static PurchaseOrderReceiveDetails LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spPurchaseOrderReceiveDetails_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    PurchaseOrderReceiveDetails result = new PurchaseOrderReceiveDetails();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of PurchaseOrderReceiveDetails objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PurchaseOrderReceiveDetails objects in the database.</returns>
        public static PurchaseOrderReceiveDetailsCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spPurchaseOrderReceiveDetails_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PurchaseOrderReceiveDetails objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PurchaseOrderReceiveDetails objects in the database ordered by the columns specified.</returns>
        public static PurchaseOrderReceiveDetailsCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPurchaseOrderReceiveDetails_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PurchaseOrderReceiveDetails objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PurchaseOrderReceiveDetails objects in the database.</returns>
        public static PurchaseOrderReceiveDetailsCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spPurchaseOrderReceiveDetails_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PurchaseOrderReceiveDetails objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the PurchaseOrderReceiveDetails objects in the database ordered by the columns specified.</returns>
        public static PurchaseOrderReceiveDetailsCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spPurchaseOrderReceiveDetails_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of PurchaseOrderReceiveDetails objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the PurchaseOrderReceiveDetails objects in the database.</returns>
        public static PurchaseOrderReceiveDetailsCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            PurchaseOrderReceiveDetailsCollection result = new PurchaseOrderReceiveDetailsCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    PurchaseOrderReceiveDetails tmp = new PurchaseOrderReceiveDetails();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a PurchaseOrderReceiveDetails object from the database.
        /// </summary>
        /// <param name="receiveDetailsId">The primary key value</param>
        public static void Delete(Guid receiveDetailsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@ReceiveDetailsId", receiveDetailsId) };
            SqlHelper.Default.ExecuteNonQuery("spPurchaseOrderReceiveDetails_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) receiveDetailsId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) receiveHeaderId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) lineNumber = reader.GetInt32(2);
                if (!reader.IsDBNull(3)) productId = reader.GetGuid(3);
                if (!reader.IsDBNull(4)) receivedQty = reader.GetDecimal(4);
                if (!reader.IsDBNull(5)) unitCost = reader.GetDecimal(5);
                if (!reader.IsDBNull(6)) discountPcn = reader.GetDecimal(6);
                if (!reader.IsDBNull(7)) netUnitCost = reader.GetDecimal(7);
                if (!reader.IsDBNull(8)) netUnitCostCoefficient = reader.GetDecimal(8);
                if (!reader.IsDBNull(9)) billQty = reader.GetDecimal(9);
                if (!reader.IsDBNull(10)) billUnitAmount = reader.GetDecimal(10);
                if (!reader.IsDBNull(11)) notes = reader.GetString(11);
            }
        }
		
        public void Delete()
        {
            Delete(this.ReceiveDetailsId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != ReceiveDetailsId)
                    this.Delete();
                Update();
            }
        }

        public Guid ReceiveDetailsId
        {
            get { return receiveDetailsId; }
            set { receiveDetailsId = value; }
        }

        public Guid ReceiveHeaderId
        {
            get { return receiveHeaderId; }
            set { receiveHeaderId = value; }
        }

        public int LineNumber
        {
            get { return lineNumber; }
            set { lineNumber = value; }
        }

        public Guid ProductId
        {
            get { return productId; }
            set { productId = value; }
        }

        public decimal ReceivedQty
        {
            get { return receivedQty; }
            set { receivedQty = value; }
        }

        public decimal UnitCost
        {
            get { return unitCost; }
            set { unitCost = value; }
        }

        public decimal DiscountPcn
        {
            get { return discountPcn; }
            set { discountPcn = value; }
        }

        public decimal NetUnitCost
        {
            get { return netUnitCost; }
            set { netUnitCost = value; }
        }

        public decimal NetUnitCostCoefficient
        {
            get { return netUnitCostCoefficient; }
            set { netUnitCostCoefficient = value; }
        }

        public decimal BillQty
        {
            get { return billQty; }
            set { billQty = value; }
        }

        public decimal BillUnitAmount
        {
            get { return billUnitAmount; }
            set { billUnitAmount = value; }
        }

        public string Notes
        {
            get { return notes; }
            set { notes = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spPurchaseOrderReceiveDetails_InsRec", "@ReceiveDetailsId", out returnedValue, parameterValues);
            
            receiveDetailsId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spPurchaseOrderReceiveDetails_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[12];
            prams[0] = GetSqlParameter("@ReceiveDetailsId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.ReceiveDetailsId);
            prams[1] = GetSqlParameter("@ReceiveHeaderId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ReceiveHeaderId);
            prams[2] = GetSqlParameter("@LineNumber", ParameterDirection.Input, SqlDbType.Int, 4, this.LineNumber);
            prams[3] = GetSqlParameter("@ProductId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ProductId);
            prams[4] = GetSqlParameter("@ReceivedQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.ReceivedQty);
            prams[5] = GetSqlParameter("@UnitCost", ParameterDirection.Input, SqlDbType.Money, 8, this.UnitCost);
            prams[6] = GetSqlParameter("@DiscountPcn", ParameterDirection.Input, SqlDbType.Decimal, 5, this.DiscountPcn);
            prams[7] = GetSqlParameter("@NetUnitCost", ParameterDirection.Input, SqlDbType.Money, 8, this.NetUnitCost);
            prams[8] = GetSqlParameter("@NetUnitCostCoefficient", ParameterDirection.Input, SqlDbType.Money, 8, this.NetUnitCostCoefficient);
            prams[9] = GetSqlParameter("@BillQty", ParameterDirection.Input, SqlDbType.Decimal, 9, this.BillQty);
            prams[10] = GetSqlParameter("@BillUnitAmount", ParameterDirection.Input, SqlDbType.Money, 8, this.BillUnitAmount);
            prams[11] = GetSqlParameter("@Notes", ParameterDirection.Input, SqlDbType.NVarChar, 20, this.Notes);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@ReceiveDetailsId", SqlDbType.UniqueIdentifier, 16, this.ReceiveDetailsId),
                GetSqlParameterWithoutDirection("@ReceiveHeaderId", SqlDbType.UniqueIdentifier, 16, this.ReceiveHeaderId),
                GetSqlParameterWithoutDirection("@LineNumber", SqlDbType.Int, 4, this.LineNumber),
                GetSqlParameterWithoutDirection("@ProductId", SqlDbType.UniqueIdentifier, 16, this.ProductId),
                GetSqlParameterWithoutDirection("@ReceivedQty", SqlDbType.Decimal, 9, this.ReceivedQty),
                GetSqlParameterWithoutDirection("@UnitCost", SqlDbType.Money, 8, this.UnitCost),
                GetSqlParameterWithoutDirection("@DiscountPcn", SqlDbType.Decimal, 5, this.DiscountPcn),
                GetSqlParameterWithoutDirection("@NetUnitCost", SqlDbType.Money, 8, this.NetUnitCost),
                GetSqlParameterWithoutDirection("@NetUnitCostCoefficient", SqlDbType.Money, 8, this.NetUnitCostCoefficient),
                GetSqlParameterWithoutDirection("@BillQty", SqlDbType.Decimal, 9, this.BillQty),
                GetSqlParameterWithoutDirection("@BillUnitAmount", SqlDbType.Money, 8, this.BillUnitAmount),
                GetSqlParameterWithoutDirection("@Notes", SqlDbType.NVarChar, 20, this.Notes)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("receiveDetailsId: " + receiveDetailsId.ToString()).Append("\r\n");
            builder.Append("receiveHeaderId: " + receiveHeaderId.ToString()).Append("\r\n");
            builder.Append("lineNumber: " + lineNumber.ToString()).Append("\r\n");
            builder.Append("productId: " + productId.ToString()).Append("\r\n");
            builder.Append("receivedQty: " + receivedQty.ToString()).Append("\r\n");
            builder.Append("unitCost: " + unitCost.ToString()).Append("\r\n");
            builder.Append("discountPcn: " + discountPcn.ToString()).Append("\r\n");
            builder.Append("netUnitCost: " + netUnitCost.ToString()).Append("\r\n");
            builder.Append("netUnitCostCoefficient: " + netUnitCostCoefficient.ToString()).Append("\r\n");
            builder.Append("billQty: " + billQty.ToString()).Append("\r\n");
            builder.Append("billUnitAmount: " + billUnitAmount.ToString()).Append("\r\n");
            builder.Append("notes: " + notes.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			PurchaseOrderReceiveDetailsCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = PurchaseOrderReceiveDetails.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = PurchaseOrderReceiveDetails.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (PurchaseOrderReceiveDetails item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.ReceiveHeaderId != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.ReceiveDetailsId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(PurchaseOrderReceiveDetails target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.ReceiveHeaderId == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				PurchaseOrderReceiveDetails parentTemplate = PurchaseOrderReceiveDetails.Load(target.ReceiveHeaderId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(PurchaseOrderReceiveDetails target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="PurchaseOrderReceiveDetails">PurchaseOrderReceiveDetails</see> objects.
    /// </summary>
    public class PurchaseOrderReceiveDetailsCollection : BindingList< PurchaseOrderReceiveDetails>
    {
	}
}
