using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.ShipmentMethod.
    /// Date Created:   2020-08-09 02:14:15
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class ShipmentMethod
    {
        private Guid key = Guid.Empty;
        private Guid methodId = Guid.Empty;
        private Guid parentMethod = Guid.Empty;
        private string methodCode = String.Empty;
        private string methodName = String.Empty;
        private string methodName_Chs = String.Empty;
        private string methodName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty ShipmentMethod object.
        /// </summary>
        public ShipmentMethod()
        {
        }
		
        /// <summary>
        /// Initialize a new ShipmentMethod object with the given parameters.
        /// </summary>
        public ShipmentMethod(Guid methodId, Guid parentMethod, string methodCode, string methodName, string methodName_Chs, string methodName_Cht)
        {
                this.methodId = methodId;
                this.parentMethod = parentMethod;
                this.methodCode = methodCode;
                this.methodName = methodName;
                this.methodName_Chs = methodName_Chs;
                this.methodName_Cht = methodName_Cht;
        }	
		
        /// <summary>
        /// Loads a ShipmentMethod object from the database using the given MethodId
        /// </summary>
        /// <param name="methodId">The primary key value</param>
        /// <returns>A ShipmentMethod object</returns>
        public static ShipmentMethod Load(Guid methodId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@MethodId", methodId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spShipmentMethod_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    ShipmentMethod result = new ShipmentMethod();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a ShipmentMethod object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A ShipmentMethod object</returns>
        public static ShipmentMethod LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spShipmentMethod_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    ShipmentMethod result = new ShipmentMethod();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of ShipmentMethod objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ShipmentMethod objects in the database.</returns>
        public static ShipmentMethodCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spShipmentMethod_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ShipmentMethod objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ShipmentMethod objects in the database ordered by the columns specified.</returns>
        public static ShipmentMethodCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spShipmentMethod_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ShipmentMethod objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ShipmentMethod objects in the database.</returns>
        public static ShipmentMethodCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spShipmentMethod_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ShipmentMethod objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the ShipmentMethod objects in the database ordered by the columns specified.</returns>
        public static ShipmentMethodCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spShipmentMethod_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of ShipmentMethod objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the ShipmentMethod objects in the database.</returns>
        public static ShipmentMethodCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            ShipmentMethodCollection result = new ShipmentMethodCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    ShipmentMethod tmp = new ShipmentMethod();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a ShipmentMethod object from the database.
        /// </summary>
        /// <param name="methodId">The primary key value</param>
        public static void Delete(Guid methodId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@MethodId", methodId) };
            SqlHelper.Default.ExecuteNonQuery("spShipmentMethod_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) methodId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentMethod = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) methodCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) methodName = reader.GetString(3);
                if (!reader.IsDBNull(4)) methodName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) methodName_Cht = reader.GetString(5);
            }
        }
		
        public void Delete()
        {
            Delete(this.MethodId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != MethodId)
                    this.Delete();
                Update();
            }
        }

        public Guid MethodId
        {
            get { return methodId; }
            set { methodId = value; }
        }

        public Guid ParentMethod
        {
            get { return parentMethod; }
            set { parentMethod = value; }
        }

        public string MethodCode
        {
            get { return methodCode; }
            set { methodCode = value; }
        }

        public string MethodName
        {
            get { return methodName; }
            set { methodName = value; }
        }

        public string MethodName_Chs
        {
            get { return methodName_Chs; }
            set { methodName_Chs = value; }
        }

        public string MethodName_Cht
        {
            get { return methodName_Cht; }
            set { methodName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spShipmentMethod_InsRec", "@MethodId", out returnedValue, parameterValues);
            
            methodId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spShipmentMethod_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@MethodId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.MethodId);
            prams[1] = GetSqlParameter("@ParentMethod", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentMethod);
            prams[2] = GetSqlParameter("@MethodCode", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.MethodCode);
            prams[3] = GetSqlParameter("@MethodName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.MethodName);
            prams[4] = GetSqlParameter("@MethodName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.MethodName_Chs);
            prams[5] = GetSqlParameter("@MethodName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.MethodName_Cht);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@MethodId", SqlDbType.UniqueIdentifier, 16, this.MethodId),
                GetSqlParameterWithoutDirection("@ParentMethod", SqlDbType.UniqueIdentifier, 16, this.ParentMethod),
                GetSqlParameterWithoutDirection("@MethodCode", SqlDbType.NVarChar, 10, this.MethodCode),
                GetSqlParameterWithoutDirection("@MethodName", SqlDbType.NVarChar, 64, this.MethodName),
                GetSqlParameterWithoutDirection("@MethodName_Chs", SqlDbType.NVarChar, 64, this.MethodName_Chs),
                GetSqlParameterWithoutDirection("@MethodName_Cht", SqlDbType.NVarChar, 64, this.MethodName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("methodId: " + methodId.ToString()).Append("\r\n");
            builder.Append("parentMethod: " + parentMethod.ToString()).Append("\r\n");
            builder.Append("methodCode: " + methodCode.ToString()).Append("\r\n");
            builder.Append("methodName: " + methodName.ToString()).Append("\r\n");
            builder.Append("methodName_Chs: " + methodName_Chs.ToString()).Append("\r\n");
            builder.Append("methodName_Cht: " + methodName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			ShipmentMethodCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = ShipmentMethod.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = ShipmentMethod.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (ShipmentMethod item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.ParentMethod != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.MethodId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(ShipmentMethod target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.ParentMethod == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				ShipmentMethod parentTemplate = ShipmentMethod.Load(target.ParentMethod);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(ShipmentMethod target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="ShipmentMethod">ShipmentMethod</see> objects.
    /// </summary>
    public class ShipmentMethodCollection : BindingList< ShipmentMethod>
    {
	}
}
