using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.StaffSecurity.
    /// Date Created:   2020-08-09 02:14:16
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class StaffSecurity
    {
        private Guid key = Guid.Empty;
        private Guid securityId = Guid.Empty;
        private Guid staffId = Guid.Empty;
        private string gradeCode = String.Empty;
        private string module = String.Empty;
        private string functions = String.Empty;
        private bool canRead;
        private bool canWrite;
        private bool canDelete;
        private bool canPost;

        /// <summary>
        /// Initialize an new empty StaffSecurity object.
        /// </summary>
        public StaffSecurity()
        {
        }
		
        /// <summary>
        /// Initialize a new StaffSecurity object with the given parameters.
        /// </summary>
        public StaffSecurity(Guid securityId, Guid staffId, string gradeCode, string module, string functions, bool canRead, bool canWrite, bool canDelete, bool canPost)
        {
                this.securityId = securityId;
                this.staffId = staffId;
                this.gradeCode = gradeCode;
                this.module = module;
                this.functions = functions;
                this.canRead = canRead;
                this.canWrite = canWrite;
                this.canDelete = canDelete;
                this.canPost = canPost;
        }	
		
        /// <summary>
        /// Loads a StaffSecurity object from the database using the given SecurityId
        /// </summary>
        /// <param name="securityId">The primary key value</param>
        /// <returns>A StaffSecurity object</returns>
        public static StaffSecurity Load(Guid securityId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@SecurityId", securityId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spStaffSecurity_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    StaffSecurity result = new StaffSecurity();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a StaffSecurity object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A StaffSecurity object</returns>
        public static StaffSecurity LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spStaffSecurity_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    StaffSecurity result = new StaffSecurity();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of StaffSecurity objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffSecurity objects in the database.</returns>
        public static StaffSecurityCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spStaffSecurity_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffSecurity objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the StaffSecurity objects in the database ordered by the columns specified.</returns>
        public static StaffSecurityCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spStaffSecurity_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffSecurity objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffSecurity objects in the database.</returns>
        public static StaffSecurityCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spStaffSecurity_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffSecurity objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the StaffSecurity objects in the database ordered by the columns specified.</returns>
        public static StaffSecurityCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spStaffSecurity_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffSecurity objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffSecurity objects in the database.</returns>
        public static StaffSecurityCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            StaffSecurityCollection result = new StaffSecurityCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    StaffSecurity tmp = new StaffSecurity();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a StaffSecurity object from the database.
        /// </summary>
        /// <param name="securityId">The primary key value</param>
        public static void Delete(Guid securityId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@SecurityId", securityId) };
            SqlHelper.Default.ExecuteNonQuery("spStaffSecurity_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) securityId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) staffId = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) gradeCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) module = reader.GetString(3);
                if (!reader.IsDBNull(4)) functions = reader.GetString(4);
                if (!reader.IsDBNull(5)) canRead = reader.GetBoolean(5);
                if (!reader.IsDBNull(6)) canWrite = reader.GetBoolean(6);
                if (!reader.IsDBNull(7)) canDelete = reader.GetBoolean(7);
                if (!reader.IsDBNull(8)) canPost = reader.GetBoolean(8);
            }
        }
		
        public void Delete()
        {
            Delete(this.SecurityId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != SecurityId)
                    this.Delete();
                Update();
            }
        }

        public Guid SecurityId
        {
            get { return securityId; }
            set { securityId = value; }
        }

        public Guid StaffId
        {
            get { return staffId; }
            set { staffId = value; }
        }

        public string GradeCode
        {
            get { return gradeCode; }
            set { gradeCode = value; }
        }

        public string Module
        {
            get { return module; }
            set { module = value; }
        }

        public string Functions
        {
            get { return functions; }
            set { functions = value; }
        }

        public bool CanRead
        {
            get { return canRead; }
            set { canRead = value; }
        }

        public bool CanWrite
        {
            get { return canWrite; }
            set { canWrite = value; }
        }

        public bool CanDelete
        {
            get { return canDelete; }
            set { canDelete = value; }
        }

        public bool CanPost
        {
            get { return canPost; }
            set { canPost = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spStaffSecurity_InsRec", "@SecurityId", out returnedValue, parameterValues);
            
            securityId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spStaffSecurity_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[9];
            prams[0] = GetSqlParameter("@SecurityId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.SecurityId);
            prams[1] = GetSqlParameter("@StaffId", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.StaffId);
            prams[2] = GetSqlParameter("@GradeCode", ParameterDirection.Input, SqlDbType.NVarChar, 2, this.GradeCode);
            prams[3] = GetSqlParameter("@Module", ParameterDirection.Input, SqlDbType.NVarChar, 20, this.Module);
            prams[4] = GetSqlParameter("@Functions", ParameterDirection.Input, SqlDbType.NVarChar, 30, this.Functions);
            prams[5] = GetSqlParameter("@CanRead", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanRead);
            prams[6] = GetSqlParameter("@CanWrite", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanWrite);
            prams[7] = GetSqlParameter("@CanDelete", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanDelete);
            prams[8] = GetSqlParameter("@CanPost", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanPost);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@SecurityId", SqlDbType.UniqueIdentifier, 16, this.SecurityId),
                GetSqlParameterWithoutDirection("@StaffId", SqlDbType.UniqueIdentifier, 16, this.StaffId),
                GetSqlParameterWithoutDirection("@GradeCode", SqlDbType.NVarChar, 2, this.GradeCode),
                GetSqlParameterWithoutDirection("@Module", SqlDbType.NVarChar, 20, this.Module),
                GetSqlParameterWithoutDirection("@Functions", SqlDbType.NVarChar, 30, this.Functions),
                GetSqlParameterWithoutDirection("@CanRead", SqlDbType.Bit, 1, this.CanRead),
                GetSqlParameterWithoutDirection("@CanWrite", SqlDbType.Bit, 1, this.CanWrite),
                GetSqlParameterWithoutDirection("@CanDelete", SqlDbType.Bit, 1, this.CanDelete),
                GetSqlParameterWithoutDirection("@CanPost", SqlDbType.Bit, 1, this.CanPost)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("securityId: " + securityId.ToString()).Append("\r\n");
            builder.Append("staffId: " + staffId.ToString()).Append("\r\n");
            builder.Append("gradeCode: " + gradeCode.ToString()).Append("\r\n");
            builder.Append("module: " + module.ToString()).Append("\r\n");
            builder.Append("functions: " + functions.ToString()).Append("\r\n");
            builder.Append("canRead: " + canRead.ToString()).Append("\r\n");
            builder.Append("canWrite: " + canWrite.ToString()).Append("\r\n");
            builder.Append("canDelete: " + canDelete.ToString()).Append("\r\n");
            builder.Append("canPost: " + canPost.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			StaffSecurityCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = StaffSecurity.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = StaffSecurity.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (StaffSecurity item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.StaffId != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.SecurityId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(StaffSecurity target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.StaffId == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				StaffSecurity parentTemplate = StaffSecurity.Load(target.StaffId);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(StaffSecurity target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="StaffSecurity">StaffSecurity</see> objects.
    /// </summary>
    public class StaffSecurityCollection : BindingList< StaffSecurity>
    {
	}
}
