using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.StaffGroup.
    /// Date Created:   2020-08-09 02:14:16
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class StaffGroup
    {
        private Guid key = Guid.Empty;
        private Guid groupId = Guid.Empty;
        private Guid parentGrade = Guid.Empty;
        private string gradeCode = String.Empty;
        private string gradeName = String.Empty;
        private string gradeName_Chs = String.Empty;
        private string gradeName_Cht = String.Empty;
        private bool canRead;
        private bool canWrite;
        private bool canDelete;
        private bool canPost;

        /// <summary>
        /// Initialize an new empty StaffGroup object.
        /// </summary>
        public StaffGroup()
        {
        }
		
        /// <summary>
        /// Initialize a new StaffGroup object with the given parameters.
        /// </summary>
        public StaffGroup(Guid groupId, Guid parentGrade, string gradeCode, string gradeName, string gradeName_Chs, string gradeName_Cht, bool canRead, bool canWrite, bool canDelete, bool canPost)
        {
                this.groupId = groupId;
                this.parentGrade = parentGrade;
                this.gradeCode = gradeCode;
                this.gradeName = gradeName;
                this.gradeName_Chs = gradeName_Chs;
                this.gradeName_Cht = gradeName_Cht;
                this.canRead = canRead;
                this.canWrite = canWrite;
                this.canDelete = canDelete;
                this.canPost = canPost;
        }	
		
        /// <summary>
        /// Loads a StaffGroup object from the database using the given GroupId
        /// </summary>
        /// <param name="groupId">The primary key value</param>
        /// <returns>A StaffGroup object</returns>
        public static StaffGroup Load(Guid groupId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@GroupId", groupId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spStaffGroup_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    StaffGroup result = new StaffGroup();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a StaffGroup object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A StaffGroup object</returns>
        public static StaffGroup LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spStaffGroup_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    StaffGroup result = new StaffGroup();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of StaffGroup objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffGroup objects in the database.</returns>
        public static StaffGroupCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spStaffGroup_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffGroup objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the StaffGroup objects in the database ordered by the columns specified.</returns>
        public static StaffGroupCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spStaffGroup_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffGroup objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffGroup objects in the database.</returns>
        public static StaffGroupCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spStaffGroup_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffGroup objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the StaffGroup objects in the database ordered by the columns specified.</returns>
        public static StaffGroupCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spStaffGroup_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of StaffGroup objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the StaffGroup objects in the database.</returns>
        public static StaffGroupCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            StaffGroupCollection result = new StaffGroupCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    StaffGroup tmp = new StaffGroup();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a StaffGroup object from the database.
        /// </summary>
        /// <param name="groupId">The primary key value</param>
        public static void Delete(Guid groupId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@GroupId", groupId) };
            SqlHelper.Default.ExecuteNonQuery("spStaffGroup_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) groupId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentGrade = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) gradeCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) gradeName = reader.GetString(3);
                if (!reader.IsDBNull(4)) gradeName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) gradeName_Cht = reader.GetString(5);
                if (!reader.IsDBNull(6)) canRead = reader.GetBoolean(6);
                if (!reader.IsDBNull(7)) canWrite = reader.GetBoolean(7);
                if (!reader.IsDBNull(8)) canDelete = reader.GetBoolean(8);
                if (!reader.IsDBNull(9)) canPost = reader.GetBoolean(9);
            }
        }
		
        public void Delete()
        {
            Delete(this.GroupId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != GroupId)
                    this.Delete();
                Update();
            }
        }

        public Guid GroupId
        {
            get { return groupId; }
            set { groupId = value; }
        }

        public Guid ParentGrade
        {
            get { return parentGrade; }
            set { parentGrade = value; }
        }

        public string GradeCode
        {
            get { return gradeCode; }
            set { gradeCode = value; }
        }

        public string GradeName
        {
            get { return gradeName; }
            set { gradeName = value; }
        }

        public string GradeName_Chs
        {
            get { return gradeName_Chs; }
            set { gradeName_Chs = value; }
        }

        public string GradeName_Cht
        {
            get { return gradeName_Cht; }
            set { gradeName_Cht = value; }
        }

        public bool CanRead
        {
            get { return canRead; }
            set { canRead = value; }
        }

        public bool CanWrite
        {
            get { return canWrite; }
            set { canWrite = value; }
        }

        public bool CanDelete
        {
            get { return canDelete; }
            set { canDelete = value; }
        }

        public bool CanPost
        {
            get { return canPost; }
            set { canPost = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spStaffGroup_InsRec", "@GroupId", out returnedValue, parameterValues);
            
            groupId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spStaffGroup_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[10];
            prams[0] = GetSqlParameter("@GroupId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.GroupId);
            prams[1] = GetSqlParameter("@ParentGrade", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentGrade);
            prams[2] = GetSqlParameter("@GradeCode", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.GradeCode);
            prams[3] = GetSqlParameter("@GradeName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.GradeName);
            prams[4] = GetSqlParameter("@GradeName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.GradeName_Chs);
            prams[5] = GetSqlParameter("@GradeName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.GradeName_Cht);
            prams[6] = GetSqlParameter("@CanRead", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanRead);
            prams[7] = GetSqlParameter("@CanWrite", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanWrite);
            prams[8] = GetSqlParameter("@CanDelete", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanDelete);
            prams[9] = GetSqlParameter("@CanPost", ParameterDirection.Input, SqlDbType.Bit, 1, this.CanPost);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@GroupId", SqlDbType.UniqueIdentifier, 16, this.GroupId),
                GetSqlParameterWithoutDirection("@ParentGrade", SqlDbType.UniqueIdentifier, 16, this.ParentGrade),
                GetSqlParameterWithoutDirection("@GradeCode", SqlDbType.NVarChar, 10, this.GradeCode),
                GetSqlParameterWithoutDirection("@GradeName", SqlDbType.NVarChar, 64, this.GradeName),
                GetSqlParameterWithoutDirection("@GradeName_Chs", SqlDbType.NVarChar, 64, this.GradeName_Chs),
                GetSqlParameterWithoutDirection("@GradeName_Cht", SqlDbType.NVarChar, 64, this.GradeName_Cht),
                GetSqlParameterWithoutDirection("@CanRead", SqlDbType.Bit, 1, this.CanRead),
                GetSqlParameterWithoutDirection("@CanWrite", SqlDbType.Bit, 1, this.CanWrite),
                GetSqlParameterWithoutDirection("@CanDelete", SqlDbType.Bit, 1, this.CanDelete),
                GetSqlParameterWithoutDirection("@CanPost", SqlDbType.Bit, 1, this.CanPost)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("groupId: " + groupId.ToString()).Append("\r\n");
            builder.Append("parentGrade: " + parentGrade.ToString()).Append("\r\n");
            builder.Append("gradeCode: " + gradeCode.ToString()).Append("\r\n");
            builder.Append("gradeName: " + gradeName.ToString()).Append("\r\n");
            builder.Append("gradeName_Chs: " + gradeName_Chs.ToString()).Append("\r\n");
            builder.Append("gradeName_Cht: " + gradeName_Cht.ToString()).Append("\r\n");
            builder.Append("canRead: " + canRead.ToString()).Append("\r\n");
            builder.Append("canWrite: " + canWrite.ToString()).Append("\r\n");
            builder.Append("canDelete: " + canDelete.ToString()).Append("\r\n");
            builder.Append("canPost: " + canPost.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			StaffGroupCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = StaffGroup.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = StaffGroup.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (StaffGroup item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.ParentGrade != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.GroupId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(StaffGroup target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.ParentGrade == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				StaffGroup parentTemplate = StaffGroup.Load(target.ParentGrade);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(StaffGroup target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="StaffGroup">StaffGroup</see> objects.
    /// </summary>
    public class StaffGroupCollection : BindingList< StaffGroup>
    {
	}
}
