using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Reflection;
using System.Text;
using Gizmox.WebGUI.Forms;
using System.Xml;

using Microsoft.Practices.EnterpriseLibrary.Data;

namespace RT2020.DAL
{
    /// <summary>
    /// This Data Access Layer Component (DALC) provides access to the data contained in the data table dbo.SupplierTerms.
    /// Date Created:   2020-08-09 02:14:17
    /// Created By:     Generated by CodeSmith version 7.0.0.15123
    /// Template:       BusinessObjects_v5.0.cst
    /// </summary>
    public class SupplierTerms
    {
        private Guid key = Guid.Empty;
        private Guid termsId = Guid.Empty;
        private Guid parentTerms = Guid.Empty;
        private string termsCode = String.Empty;
        private string termsName = String.Empty;
        private string termsName_Chs = String.Empty;
        private string termsName_Cht = String.Empty;

        /// <summary>
        /// Initialize an new empty SupplierTerms object.
        /// </summary>
        public SupplierTerms()
        {
        }
		
        /// <summary>
        /// Initialize a new SupplierTerms object with the given parameters.
        /// </summary>
        public SupplierTerms(Guid termsId, Guid parentTerms, string termsCode, string termsName, string termsName_Chs, string termsName_Cht)
        {
                this.termsId = termsId;
                this.parentTerms = parentTerms;
                this.termsCode = termsCode;
                this.termsName = termsName;
                this.termsName_Chs = termsName_Chs;
                this.termsName_Cht = termsName_Cht;
        }	
		
        /// <summary>
        /// Loads a SupplierTerms object from the database using the given TermsId
        /// </summary>
        /// <param name="termsId">The primary key value</param>
        /// <returns>A SupplierTerms object</returns>
        public static SupplierTerms Load(Guid termsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TermsId", termsId) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spSupplierTerms_SelRec", parameterValues))
            {
                if (reader.Read())
                {
                    SupplierTerms result = new SupplierTerms();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }

        /// <summary>
        /// Loads a SupplierTerms object from the database using the given where clause
        /// </summary>
        /// <param name="whereClause">The filter expression for the query</param>
        /// <returns>A SupplierTerms object</returns>
        public static SupplierTerms LoadWhere(string whereClause)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader("spSupplierTerms_SelAll", parameterValues))
            {
                if (reader.Read())
                {
                    SupplierTerms result = new SupplierTerms();
                    result.LoadFromReader(reader);
                    return result;
                }
                else
                    return null;
            }
        }
		
        /// <summary>
        /// Loads a collection of SupplierTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the SupplierTerms objects in the database.</returns>
        public static SupplierTermsCollection LoadCollection()
        {
            SqlParameter[] parms = new SqlParameter[] {};
            return LoadCollection("spSupplierTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of SupplierTerms objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the SupplierTerms objects in the database ordered by the columns specified.</returns>
        public static SupplierTermsCollection LoadCollection(string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spSupplierTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of SupplierTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the SupplierTerms objects in the database.</returns>
        public static SupplierTermsCollection LoadCollection(string whereClause)
        {
            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause) };
            return LoadCollection("spSupplierTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of SupplierTerms objects from the database ordered by the columns specified.
        /// </summary>
        /// <returns>A collection containing all of the SupplierTerms objects in the database ordered by the columns specified.</returns>
        public static SupplierTermsCollection LoadCollection(string whereClause, string[] orderByColumns, bool ascending)
        {
            StringBuilder orderClause = new StringBuilder();
            for (int i = 0; i < orderByColumns.Length; i++)
            {
                orderClause.Append(orderByColumns[i]);

                if (i != orderByColumns.Length-1)
                    orderClause.Append(", ");
            }

            if (ascending)
                orderClause.Append(" ASC");
            else
                orderClause.Append(" DESC");

            SqlParameter[] parms = new SqlParameter[] { new SqlParameter("@WhereClause", whereClause), new SqlParameter("@OrderBy", orderClause.ToString()) };
            return LoadCollection("spSupplierTerms_SelAll", parms);
        }

        /// <summary>
        /// Loads a collection of SupplierTerms objects from the database.
        /// </summary>
        /// <returns>A collection containing all of the SupplierTerms objects in the database.</returns>
        public static SupplierTermsCollection LoadCollection(string spName, SqlParameter[] parms)
        {
            SupplierTermsCollection result = new SupplierTermsCollection();
            using (SqlDataReader reader = SqlHelper.Default.ExecuteReader(spName, parms))
            {
                while (reader.Read())
                {
                    SupplierTerms tmp = new SupplierTerms();
                    tmp.LoadFromReader(reader);
                    result.Add(tmp);
                }
            }
            return result;
        }

        /// <summary>
        /// Deletes a SupplierTerms object from the database.
        /// </summary>
        /// <param name="termsId">The primary key value</param>
        public static void Delete(Guid termsId)
        {
            SqlParameter[] parameterValues = new SqlParameter[] { new SqlParameter("@TermsId", termsId) };
            SqlHelper.Default.ExecuteNonQuery("spSupplierTerms_DelRec", parameterValues);
        }

		
        public void LoadFromReader(SqlDataReader reader)
        {
            if (reader != null && !reader.IsClosed)
            {
                key = reader.GetGuid(0);
                if (!reader.IsDBNull(0)) termsId = reader.GetGuid(0);
                if (!reader.IsDBNull(1)) parentTerms = reader.GetGuid(1);
                if (!reader.IsDBNull(2)) termsCode = reader.GetString(2);
                if (!reader.IsDBNull(3)) termsName = reader.GetString(3);
                if (!reader.IsDBNull(4)) termsName_Chs = reader.GetString(4);
                if (!reader.IsDBNull(5)) termsName_Cht = reader.GetString(5);
            }
        }
		
        public void Delete()
        {
            Delete(this.TermsId);
        }

        public void Save()
        {
            //  We use the key field which will have its default value unless it is set by Load(). When we save we can know if
            //  we need to do an insert (key == null) an update (key == primaryKey) or a 
            //  delete+update (key != null && key != primaryKey)

            if (key == Guid.Empty)
                Insert();
            else
            {
                if (key != TermsId)
                    this.Delete();
                Update();
            }
        }

        public Guid TermsId
        {
            get { return termsId; }
            set { termsId = value; }
        }

        public Guid ParentTerms
        {
            get { return parentTerms; }
            set { parentTerms = value; }
        }

        public string TermsCode
        {
            get { return termsCode; }
            set { termsCode = value; }
        }

        public string TermsName
        {
            get { return termsName; }
            set { termsName = value; }
        }

        public string TermsName_Chs
        {
            get { return termsName_Chs; }
            set { termsName_Chs = value; }
        }

        public string TermsName_Cht
        {
            get { return termsName_Cht; }
            set { termsName_Cht = value; }
        }


        private void Insert()
        {
            SqlParameter[] parameterValues = GetInsertParameterValues();
            object returnedValue = null;
			
            SqlHelper.Default.ExecuteNonQuery("spSupplierTerms_InsRec", "@TermsId", out returnedValue, parameterValues);
            
            termsId = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
            key = returnedValue != null ? (Guid)returnedValue : Guid.Empty;
        }

        private void Update()
        {
            SqlParameter[] parameterValues = GetUpdateParameterValues();
            
			SqlHelper.Default.ExecuteNonQuery("spSupplierTerms_UpdRec", parameterValues);
        }
        
        /// <summary>
        /// Gets the SQL parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="direction">The direction.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameter(string name, ParameterDirection direction, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            p.Direction = direction;
            return p;
        }

        private SqlParameter[] GetInsertParameterValues()
        {
            SqlParameter[] prams = new SqlParameter[6];
            prams[0] = GetSqlParameter("@TermsId", ParameterDirection.Output, SqlDbType.UniqueIdentifier, 16, this.TermsId);
            prams[1] = GetSqlParameter("@ParentTerms", ParameterDirection.Input, SqlDbType.UniqueIdentifier, 16, this.ParentTerms);
            prams[2] = GetSqlParameter("@TermsCode", ParameterDirection.Input, SqlDbType.NVarChar, 10, this.TermsCode);
            prams[3] = GetSqlParameter("@TermsName", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName);
            prams[4] = GetSqlParameter("@TermsName_Chs", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName_Chs);
            prams[5] = GetSqlParameter("@TermsName_Cht", ParameterDirection.Input, SqlDbType.NVarChar, 64, this.TermsName_Cht);
            return prams;
        }
		
        /// <summary>
        /// Gets the SQL parameter without direction.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="dbType">Type of the db.</param>
        /// <param name="size">The size.</param>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        private SqlParameter GetSqlParameterWithoutDirection(string name, SqlDbType dbType, int size, object value)
        {
            SqlParameter p = new SqlParameter(name, dbType, size);
            p.Value = value;
            return p;
        }
        
        private SqlParameter[] GetUpdateParameterValues()
        {
            return new SqlParameter[] 
            {
                GetSqlParameterWithoutDirection("@TermsId", SqlDbType.UniqueIdentifier, 16, this.TermsId),
                GetSqlParameterWithoutDirection("@ParentTerms", SqlDbType.UniqueIdentifier, 16, this.ParentTerms),
                GetSqlParameterWithoutDirection("@TermsCode", SqlDbType.NVarChar, 10, this.TermsCode),
                GetSqlParameterWithoutDirection("@TermsName", SqlDbType.NVarChar, 64, this.TermsName),
                GetSqlParameterWithoutDirection("@TermsName_Chs", SqlDbType.NVarChar, 64, this.TermsName_Chs),
                GetSqlParameterWithoutDirection("@TermsName_Cht", SqlDbType.NVarChar, 64, this.TermsName_Cht)
            };
        }

        public override string ToString()
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("termsId: " + termsId.ToString()).Append("\r\n");
            builder.Append("parentTerms: " + parentTerms.ToString()).Append("\r\n");
            builder.Append("termsCode: " + termsCode.ToString()).Append("\r\n");
            builder.Append("termsName: " + termsName.ToString()).Append("\r\n");
            builder.Append("termsName_Chs: " + termsName_Chs.ToString()).Append("\r\n");
            builder.Append("termsName_Cht: " + termsName_Cht.ToString()).Append("\r\n");
            builder.Append("\r\n");
            return builder.ToString();
        }	
		
		#region Load ComboBox
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, new string[]{ TextField });
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, false, string.Empty, string.Empty, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, new String[] { TextField });
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. "FieldName"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string TextField, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			string [] textField = {TextField};
			LoadCombo(ref ddList, textField, "{0}", SwitchLocale, BlankLine, BlankLineText, ParentFilter, WhereClause, OrderBy);
		}

        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string WhereClause, string[] OrderBy)
		{
			LoadCombo(ref ddList, TextField, TextFormatString, SwitchLocale, BlankLine, BlankLineText, string.Empty, WhereClause, OrderBy);
		}
		
        /// <summary>
        /// Only support the ComboBox control from WinForm/Visual WebGUI
        /// </summary>
        /// <param name="ddList">the ComboBox control from WinForm/Visual WebGUI</param>
        /// <param name="TextField">e.g. new string[]{"FieldName1", "FieldName2", ...}</param>
        /// <param name="TextFormatString">e.g. "{0} - {1}"</param>
        /// <param name="SwitchLocale">Can be localized, if the FieldName has locale suffix, e.g. '_chs'</param>
        /// <param name="BlankLine">add blank label text to ComboBox or not</param>
        /// <param name="BlankLineText">the blank label text</param>
        /// <param name="ParentFilter">e.g. "ForeignFieldName = 'value'"</param>
        /// <param name="WhereClause">Where Clause for SQL Statement. e.g. "FieldName = 'SomeCondition'"</param>
        /// <param name="OrderBy">Sorting order, string array, e.g. {"FieldName1", "FiledName2"}</param>
		public static void LoadCombo(ref ComboBox ddList, string [] TextField, string TextFormatString, bool SwitchLocale, bool BlankLine, string BlankLineText, string ParentFilter, string WhereClause, string[] OrderBy)
		{
			if (SwitchLocale)
			{
				TextField = GetSwitchLocale(TextField);
			}
			ddList.Items.Clear();						
			
			SupplierTermsCollection source;
            
            if(OrderBy == null || OrderBy.Length == 0)
            {
			    OrderBy = TextField;
            }
			
			if (WhereClause.Length > 0)
			{
				source = SupplierTerms.LoadCollection(WhereClause, OrderBy, true);
			}
			else
			{
				source = SupplierTerms.LoadCollection(OrderBy, true);
			}
			
            Common.ComboList sourceList = new Common.ComboList();

			if (BlankLine)
			{
                sourceList.Add(new Common.ComboItem(BlankLineText, Guid.Empty));
			}
			
			foreach (SupplierTerms item in source)
			{
				bool filter = false;
				if (ParentFilter.Trim() != String.Empty)
				{
					filter = true;
					if (item.ParentTerms != Guid.Empty)
					{
						filter = IgnorThis(item, ParentFilter);
					}
				}
				if (!(filter))
				{
                    string code = GetFormatedText(item, TextField, TextFormatString);
                    sourceList.Add(new Common.ComboItem(code, item.TermsId));
				}
			}			

            ddList.DataSource = sourceList;
            ddList.DisplayMember = "Code";
            ddList.ValueMember = "Id";
			
			if (ddList.Items.Count > 0)
			{
			    ddList.SelectedIndex = 0;
            }
		}
		
		#endregion
		
		
		private static bool IgnorThis(SupplierTerms target, string parentFilter)
		{
			bool result = true;
			parentFilter = parentFilter.Replace(" ", "");		// remove spaces
			parentFilter = parentFilter.Replace("'", "");		// remove '
			string [] parsed = parentFilter.Split('=');			// parse

			if (target.ParentTerms == Guid.Empty)
			{
				PropertyInfo pi = target.GetType().GetProperty(parsed[0]);
				string filterField = (string)pi.GetValue(target, null);
				if (filterField.ToLower() == parsed[1].ToLower())
				{
					result = false;
				}
			}
			else
			{
				SupplierTerms parentTemplate = SupplierTerms.Load(target.ParentTerms);
				result = IgnorThis(parentTemplate, parentFilter);
			}
			return result;
		}

		private static string GetFormatedText(SupplierTerms target, string [] textField, string textFormatString)
		{
			for (int i = 0; i < textField.Length; i++)
			{
				PropertyInfo pi = target.GetType().GetProperty(textField[i]);
				textFormatString = textFormatString.Replace("{" + i.ToString() +"}", pi != null ? pi.GetValue(target, null).ToString() : string.Empty);
			}
			return textFormatString;
		}
		
		private static string [] GetSwitchLocale(string [] source)
		{
			switch (Common.Config.CurrentLanguageId)
			{
				case 2:
					source[source.Length - 1] += "_Chs";
					break;
				case 3:
					source[source.Length - 1] += "_Cht";
					break;
			}
			return source;
		}
    }


    /// <summary>
    /// Represents a collection of <see cref="SupplierTerms">SupplierTerms</see> objects.
    /// </summary>
    public class SupplierTermsCollection : BindingList< SupplierTerms>
    {
	}
}
