//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://synergyis.biz/SystemInfo.xsd", ClrNamespace="synergyis.biz.SystemInfo.xsd")]

namespace RT2020.Services.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemInfo", Namespace="http://synergyis.biz/SystemInfo.xsd")]
    public partial class SystemInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SystemInfoIdField;
        
        private string ShopNumberField;
        
        private string CompanyNameField;
        
        private string BasicCurrencyField;
        
        private string BarcodeLabelFormatField;
        
        private int LastMonthEndField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string SystemInfoId
        {
            get
            {
                return this.SystemInfoIdField;
            }
            set
            {
                this.SystemInfoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ShopNumber
        {
            get
            {
                return this.ShopNumberField;
            }
            set
            {
                this.ShopNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BasicCurrency
        {
            get
            {
                return this.BasicCurrencyField;
            }
            set
            {
                this.BasicCurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BarcodeLabelFormat
        {
            get
            {
                return this.BarcodeLabelFormatField;
            }
            set
            {
                this.BarcodeLabelFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int LastMonthEnd
        {
            get
            {
                return this.LastMonthEndField;
            }
            set
            {
                this.LastMonthEndField = value;
            }
        }
    }
}
